/*
 * ejs.io.slots.h -- Property slot definitions for the "ejs.io" module
 *
 * This file is generated by ec
 *
 * Slot definitions. Version 1.1.1.
 */

#ifndef _h_SLOTS_EjsIoSlots
#define _h_SLOTS_EjsIoSlots 1


/**
 * Slots for the "ejs.io" module 
 */


/**
 *   Class property slots for the "global" class 
 */

/**
 * Instance slots for "global" type 
 */

/**
 * 
 *    Local slots for methods in type global 
 */


/**
 *   Class property slots for the "BinaryStream" class 
 */
#define ES_ejs_io_BinaryStream__origin                                 6
#define ES_ejs_io_BinaryStream_BinaryStream                            6
#define ES_ejs_io_BinaryStream__initializer__BinaryStream_initializer  7
#define ES_ejs_io_BinaryStream_BigEndian                               8
#define ES_ejs_io_BinaryStream_LittleEndian                            9
#define ES_ejs_io_BinaryStream_available                               10
#define ES_ejs_io_BinaryStream_close                                   11
#define ES_ejs_io_BinaryStream_endian                                  12
#define ES_ejs_io_BinaryStream_set_endian                              13
#define ES_ejs_io_BinaryStream_flush                                   14
#define ES_ejs_io_BinaryStream_read                                    15
#define ES_ejs_io_BinaryStream_readBoolean                             16
#define ES_ejs_io_BinaryStream_readByte                                17
#define ES_ejs_io_BinaryStream_readDate                                18
#define ES_ejs_io_BinaryStream_readDouble                              19
#define ES_ejs_io_BinaryStream_readInteger                             20
#define ES_ejs_io_BinaryStream_readLong                                21
#define ES_ejs_io_BinaryStream_readString                              22
#define ES_ejs_io_BinaryStream_readXML                                 23
#define ES_ejs_io_BinaryStream_write                                   24
#define ES_ejs_io_BinaryStream_writeByte                               25
#define ES_ejs_io_BinaryStream_writeShort                              26
#define ES_ejs_io_BinaryStream_writeDouble                             27
#define ES_ejs_io_BinaryStream_writeInteger                            28
#define ES_ejs_io_BinaryStream_writeLong                               29
#define ES_ejs_io_BinaryStream_NUM_CLASS_PROP                          30

/**
 * Instance slots for "BinaryStream" type 
 */
#define ES_ejs_io_BinaryStream_inbuf                                   0
#define ES_ejs_io_BinaryStream_outbuf                                  1
#define ES_ejs_io_BinaryStream_nextStream                              2
#define ES_ejs_io_BinaryStream_NUM_INSTANCE_PROP                       3

/**
 * 
 *    Local slots for methods in type BinaryStream 
 */
#define ES_ejs_io_BinaryStream_BinaryStream_stream                     0
#define ES_ejs_io_BinaryStream_BinaryStream___fun_5984__               1
#define ES_ejs_io_BinaryStream_BinaryStream___fun_6005__               2
#define ES_ejs_io_BinaryStream_close_graceful                          0
#define ES_ejs_io_BinaryStream_set_endian_value                        0
#define ES_ejs_io_BinaryStream_flush_graceful                          0
#define ES_ejs_io_BinaryStream_read_buffer                             0
#define ES_ejs_io_BinaryStream_read_offset                             1
#define ES_ejs_io_BinaryStream_read_count                              2
#define ES_ejs_io_BinaryStream_readString_count                        0
#define ES_ejs_io_BinaryStream_readXML_data                            0
#define ES_ejs_io_BinaryStream_readXML_s                               1
#define ES_ejs_io_BinaryStream_write_data                              0
#define ES_ejs_io_BinaryStream_write_count                             1
#define ES_ejs_io_BinaryStream_write__hoisted_2_i                      2
#define ES_ejs_io_BinaryStream_writeByte_data                          0
#define ES_ejs_io_BinaryStream_writeShort_data                         0
#define ES_ejs_io_BinaryStream_writeDouble_data                        0
#define ES_ejs_io_BinaryStream_writeInteger_data                       0
#define ES_ejs_io_BinaryStream_writeLong_data                          0


/**
 *   Class property slots for the "File" class 
 */
#define ES_ejs_io_File__origin                                         6
#define ES_ejs_io_File_File                                            6
#define ES_ejs_io_File_canRead                                         7
#define ES_ejs_io_File_canWrite                                        8
#define ES_ejs_io_File_close                                           9
#define ES_ejs_io_File_flush                                           10
#define ES_ejs_io_File_isOpen                                          11
#define ES_ejs_io_File_open                                            12
#define ES_ejs_io_File_options                                         13
#define ES_ejs_io_File_path                                            14
#define ES_ejs_io_File_position                                        15
#define ES_ejs_io_File_set_position                                    16
#define ES_ejs_io_File_read                                            17
#define ES_ejs_io_File_readBytes                                       18
#define ES_ejs_io_File_readString                                      19
#define ES_ejs_io_File_remove                                          20
#define ES_ejs_io_File_size                                            21
#define ES_ejs_io_File_truncate                                        22
#define ES_ejs_io_File_write                                           23
#define ES_ejs_io_File_NUM_CLASS_PROP                                  24

/**
 * Instance slots for "File" type 
 */
#define ES_ejs_io_File_NUM_INSTANCE_PROP                               0

/**
 * 
 *    Local slots for methods in type File 
 */
#define ES_ejs_io_File_File_path                                       0
#define ES_ejs_io_File_File_options                                    1
#define ES_ejs_io_File_close_graceful                                  0
#define ES_ejs_io_File_flush_graceful                                  0
#define ES_ejs_io_File_open_options                                    0
#define ES_ejs_io_File_set_position_loc                                0
#define ES_ejs_io_File_read_buffer                                     0
#define ES_ejs_io_File_read_offset                                     1
#define ES_ejs_io_File_read_count                                      2
#define ES_ejs_io_File_readBytes_count                                 0
#define ES_ejs_io_File_readString_count                                0
#define ES_ejs_io_File_truncate_value                                  0
#define ES_ejs_io_File_write_items                                     0


/**
 *   Class property slots for the "FileSystem" class 
 */
#define ES_ejs_io_FileSystem__origin                                   6
#define ES_ejs_io_FileSystem_FileSystem                                6
#define ES_ejs_io_FileSystem_hasDrives                                 7
#define ES_ejs_io_FileSystem_newline                                   8
#define ES_ejs_io_FileSystem_set_newline                               9
#define ES_ejs_io_FileSystem_root                                      10
#define ES_ejs_io_FileSystem_separators                                11
#define ES_ejs_io_FileSystem_set_separators                            12
#define ES_ejs_io_FileSystem_NUM_CLASS_PROP                            13

/**
 * Instance slots for "FileSystem" type 
 */
#define ES_ejs_io_FileSystem_NUM_INSTANCE_PROP                         0

/**
 * 
 *    Local slots for methods in type FileSystem 
 */
#define ES_ejs_io_FileSystem_FileSystem_path                           0
#define ES_ejs_io_FileSystem_set_newline_terminator                    0
#define ES_ejs_io_FileSystem_set_separators_sep                        0


/**
 *   Class property slots for the "Http" class 
 */
#define ES_ejs_io_Http__origin                                         6
#define ES_ejs_io_Http_Http                                            6
#define ES_ejs_io_Http__initializer__Http_initializer                  7
#define ES_ejs_io_Http_Continue                                        8
#define ES_ejs_io_Http_Ok                                              9
#define ES_ejs_io_Http_Created                                         10
#define ES_ejs_io_Http_Accepted                                        11
#define ES_ejs_io_Http_NotAuthoritative                                12
#define ES_ejs_io_Http_NoContent                                       13
#define ES_ejs_io_Http_Reset                                           14
#define ES_ejs_io_Http_PartialContent                                  15
#define ES_ejs_io_Http_MultipleChoice                                  16
#define ES_ejs_io_Http_MovedPermanently                                17
#define ES_ejs_io_Http_MovedTemporarily                                18
#define ES_ejs_io_Http_SeeOther                                        19
#define ES_ejs_io_Http_NotModified                                     20
#define ES_ejs_io_Http_UseProxy                                        21
#define ES_ejs_io_Http_BadRequest                                      22
#define ES_ejs_io_Http_Unauthorized                                    23
#define ES_ejs_io_Http_PaymentRequired                                 24
#define ES_ejs_io_Http_Forbidden                                       25
#define ES_ejs_io_Http_NotFound                                        26
#define ES_ejs_io_Http_BadMethod                                       27
#define ES_ejs_io_Http_NotAcceptable                                   28
#define ES_ejs_io_Http_ProxyAuthRequired                               29
#define ES_ejs_io_Http_RequestTimeout                                  30
#define ES_ejs_io_Http_Conflict                                        31
#define ES_ejs_io_Http_Gone                                            32
#define ES_ejs_io_Http_LengthRequired                                  33
#define ES_ejs_io_Http_PrecondFailed                                   34
#define ES_ejs_io_Http_EntityTooLarge                                  35
#define ES_ejs_io_Http_UriTooLong                                      36
#define ES_ejs_io_Http_UnsupportedMedia                                37
#define ES_ejs_io_Http_BadRange                                        38
#define ES_ejs_io_Http_ServerError                                     39
#define ES_ejs_io_Http_NotImplemented                                  40
#define ES_ejs_io_Http_BadGateway                                      41
#define ES_ejs_io_Http_ServiceUnavailable                              42
#define ES_ejs_io_Http_GatewayTimeout                                  43
#define ES_ejs_io_Http_VersionNotSupported                             44
#define ES_ejs_io_Http_Read                                            45
#define ES_ejs_io_Http_Write                                           46
#define ES_ejs_io_Http_addHeader                                       47
#define ES_ejs_io_Http_available                                       48
#define ES_ejs_io_Http_chunked                                         49
#define ES_ejs_io_Http_set_chunked                                     50
#define ES_ejs_io_Http_close                                           51
#define ES_ejs_io_Http_connect                                         52
#define ES_ejs_io_Http_certificate                                     53
#define ES_ejs_io_Http_set_certificate                                 54
#define ES_ejs_io_Http_code                                            55
#define ES_ejs_io_Http_codeString                                      56
#define ES_ejs_io_Http_contentEncoding                                 57
#define ES_ejs_io_Http_contentLength                                   58
#define ES_ejs_io_Http_set_contentLength                               59
#define ES_ejs_io_Http_bodyLength                                      60
#define ES_ejs_io_Http_set_bodyLength                                  61
#define ES_ejs_io_Http_contentType                                     62
#define ES_ejs_io_Http_date                                            63
#define ES_ejs_io_Http_del                                             64
#define ES_ejs_io_Http_expires                                         65
#define ES_ejs_io_Http_flush                                           66
#define ES_ejs_io_Http_followRedirects                                 67
#define ES_ejs_io_Http_set_followRedirects                             68
#define ES_ejs_io_Http_form                                            69
#define ES_ejs_io_Http_get                                             70
#define ES_ejs_io_Http_head                                            71
#define ES_ejs_io_Http_header                                          72
#define ES_ejs_io_Http_headers                                         73
#define ES_ejs_io_Http_isSecure                                        74
#define ES_ejs_io_Http_key                                             75
#define ES_ejs_io_Http_set_key                                         76
#define ES_ejs_io_Http_lastModified                                    77
#define ES_ejs_io_Http_method                                          78
#define ES_ejs_io_Http_set_method                                      79
#define ES_ejs_io_Http_mimeType                                        80
#define ES_ejs_io_Http_options                                         81
#define ES_ejs_io_Http_post                                            82
#define ES_ejs_io_Http_put                                             83
#define ES_ejs_io_Http_read                                            84
#define ES_ejs_io_Http_readString                                      85
#define ES_ejs_io_Http_readLines                                       86
#define ES_ejs_io_Http_readXml                                         87
#define ES_ejs_io_Http_response                                        88
#define ES_ejs_io_Http_retries                                         89
#define ES_ejs_io_Http_set_retries                                     90
#define ES_ejs_io_Http_setCallback                                     91
#define ES_ejs_io_Http_setCredentials                                  92
#define ES_ejs_io_Http_timeout                                         93
#define ES_ejs_io_Http_set_timeout                                     94
#define ES_ejs_io_Http_trace                                           95
#define ES_ejs_io_Http_upload                                          96
#define ES_ejs_io_Http_uri                                             97
#define ES_ejs_io_Http_set_uri                                         98
#define ES_ejs_io_Http_wait                                            99
#define ES_ejs_io_Http_write                                           100
#define ES_ejs_io_Http_NUM_CLASS_PROP                                  101

/**
 * Instance slots for "Http" type 
 */
#define ES_ejs_io_Http__response                                       0
#define ES_ejs_io_Http_NUM_INSTANCE_PROP                               1

/**
 * 
 *    Local slots for methods in type Http 
 */
#define ES_ejs_io_Http_Http_uri                                        0
#define ES_ejs_io_Http_addHeader_key                                   0
#define ES_ejs_io_Http_addHeader_value                                 1
#define ES_ejs_io_Http_addHeader_overwrite                             2
#define ES_ejs_io_Http_set_chunked_value                               0
#define ES_ejs_io_Http_close_graceful                                  0
#define ES_ejs_io_Http_connect_uri                                     0
#define ES_ejs_io_Http_connect_data                                    1
#define ES_ejs_io_Http_set_certificate_certFile                        0
#define ES_ejs_io_Http_set_contentLength_length                        0
#define ES_ejs_io_Http_set_bodyLength_value                            0
#define ES_ejs_io_Http_del_uri                                         0
#define ES_ejs_io_Http_del_data                                        1
#define ES_ejs_io_Http_flush_graceful                                  0
#define ES_ejs_io_Http_set_followRedirects_flag                        0
#define ES_ejs_io_Http_form_uri                                        0
#define ES_ejs_io_Http_form_postData                                   1
#define ES_ejs_io_Http_get_uri                                         0
#define ES_ejs_io_Http_get_data                                        1
#define ES_ejs_io_Http_head_uri                                        0
#define ES_ejs_io_Http_header_key                                      0
#define ES_ejs_io_Http_set_key_keyFile                                 0
#define ES_ejs_io_Http_set_method_name                                 0
#define ES_ejs_io_Http_mimeType_path                                   0
#define ES_ejs_io_Http_options_uri                                     0
#define ES_ejs_io_Http_post_uri                                        0
#define ES_ejs_io_Http_post_data                                       1
#define ES_ejs_io_Http_put_uri                                         0
#define ES_ejs_io_Http_put_data                                        1
#define ES_ejs_io_Http_read_buffer                                     0
#define ES_ejs_io_Http_read_offset                                     1
#define ES_ejs_io_Http_read_count                                      2
#define ES_ejs_io_Http_readString_count                                0
#define ES_ejs_io_Http_readLines_count                                 0
#define ES_ejs_io_Http_set_retries_count                               0
#define ES_ejs_io_Http_setCallback_eventMask                           0
#define ES_ejs_io_Http_setCallback_cb                                  1
#define ES_ejs_io_Http_setCredentials_username                         0
#define ES_ejs_io_Http_setCredentials_password                         1
#define ES_ejs_io_Http_set_timeout_timeout                             0
#define ES_ejs_io_Http_trace_uri                                       0
#define ES_ejs_io_Http_upload_url                                      0
#define ES_ejs_io_Http_upload_files                                    1
#define ES_ejs_io_Http_upload_fields                                   2
#define ES_ejs_io_Http_upload_boundary                                 3
#define ES_ejs_io_Http_upload_buf                                      4
#define ES_ejs_io_Http_upload_http                                     5
#define ES_ejs_io_Http_upload___fun_7476__                             6
#define ES_ejs_io_Http_upload__hoisted_7_key                           7
#define ES_ejs_io_Http_upload__hoisted_8_key                           8
#define ES_ejs_io_Http_set_uri_newUri                                  0
#define ES_ejs_io_Http_wait_timeout                                    0
#define ES_ejs_io_Http_write_data                                      0


/**
 *   Class property slots for the "HttpDataEvent" class 
 */
#define ES_ejs_io_HttpDataEvent__origin                                11
#define ES_ejs_io_HttpDataEvent_HttpDataEvent                          11
#define ES_ejs_io_HttpDataEvent__initializer__HttpDataEvent_initializer 12
#define ES_ejs_io_HttpDataEvent_NUM_CLASS_PROP                         13

/**
 * Instance slots for "HttpDataEvent" type 
 */
#define ES_ejs_io_HttpDataEvent_eventMask                              4
#define ES_ejs_io_HttpDataEvent_NUM_INSTANCE_PROP                      5


/**
 *   Class property slots for the "HttpErrorEvent" class 
 */
#define ES_ejs_io_HttpErrorEvent__origin                               11
#define ES_ejs_io_HttpErrorEvent_HttpErrorEvent                        11
#define ES_ejs_io_HttpErrorEvent__initializer__HttpErrorEvent_initializer 12
#define ES_ejs_io_HttpErrorEvent_NUM_CLASS_PROP                        13

/**
 * Instance slots for "HttpErrorEvent" type 
 */
#define ES_ejs_io_HttpErrorEvent_NUM_INSTANCE_PROP                     4


/**
 *   Class property slots for the "Path" class 
 */
#define ES_ejs_io_Path__origin                                         6
#define ES_ejs_io_Path_Path                                            6
#define ES_ejs_io_Path_absolute                                        7
#define ES_ejs_io_Path_accessed                                        8
#define ES_ejs_io_Path_basename                                        9
#define ES_ejs_io_Path_components                                      10
#define ES_ejs_io_Path_contains                                        11
#define ES_ejs_io_Path_copy                                            12
#define ES_ejs_io_Path_created                                         13
#define ES_ejs_io_Path_dirname                                         14
#define ES_ejs_io_Path_endsWith                                        15
#define ES_ejs_io_Path_exists                                          16
#define ES_ejs_io_Path_extension                                       17
#define ES_ejs_io_Path_find                                            18
#define ES_ejs_io_Path_files                                           19
#define ES_ejs_io_Path_hasDrive                                        20
#define ES_ejs_io_Path_isAbsolute                                      21
#define ES_ejs_io_Path_isDir                                           22
#define ES_ejs_io_Path_isLink                                          23
#define ES_ejs_io_Path_isRegular                                       24
#define ES_ejs_io_Path_isRelative                                      25
#define ES_ejs_io_Path_join                                            26
#define ES_ejs_io_Path_joinExt                                         27
#define ES_ejs_io_Path_linkTarget                                      28
#define ES_ejs_io_Path_makeDir                                         29
#define ES_ejs_io_Path_makeLink                                        30
#define ES_ejs_io_Path_makeTemp                                        31
#define ES_ejs_io_Path_map                                             32
#define ES_ejs_io_Path_mimeType                                        33
#define ES_ejs_io_Path_modified                                        34
#define ES_ejs_io_Path_name                                            35
#define ES_ejs_io_Path_natural                                         36
#define ES_ejs_io_Path_normalize                                       37
#define ES_ejs_io_Path_open                                            38
#define ES_ejs_io_Path_openTextStream                                  39
#define ES_ejs_io_Path_openBinaryStream                                40
#define ES_ejs_io_Path_parent                                          41
#define ES_ejs_io_Path_perms                                           42
#define ES_ejs_io_Path_set_perms                                       43
#define ES_ejs_io_Path_portable                                        44
#define ES_ejs_io_Path_readBytes                                       45
#define ES_ejs_io_Path_readLines                                       46
#define ES_ejs_io_Path_readString                                      47
#define ES_ejs_io_Path_readXML                                         48
#define ES_ejs_io_Path_relative                                        49
#define ES_ejs_io_Path_remove                                          50
#define ES_ejs_io_Path_removeAll                                       51
#define ES_ejs_io_Path_rename                                          52
#define ES_ejs_io_Path_replaceExt                                      53
#define ES_ejs_io_Path_resolve                                         54
#define ES_ejs_io_Path_same                                            55
#define ES_ejs_io_Path_separator                                       56
#define ES_ejs_io_Path_size                                            57
#define ES_ejs_io_Path_startsWith                                      58
#define ES_ejs_io_Path_toLower                                         59
#define ES_ejs_io_Path_trimEnd                                         60
#define ES_ejs_io_Path_trimExt                                         61
#define ES_ejs_io_Path_trimStart                                       62
#define ES_ejs_io_Path_truncate                                        63
#define ES_ejs_io_Path_write                                           64
#define ES_ejs_io_Path_NUM_CLASS_PROP                                  65

/**
 * Instance slots for "Path" type 
 */
#define ES_ejs_io_Path_NUM_INSTANCE_PROP                               0

/**
 * 
 *    Local slots for methods in type Path 
 */
#define ES_ejs_io_Path_Path_path                                       0
#define ES_ejs_io_Path_contains_pattern                                0
#define ES_ejs_io_Path_copy_target                                     0
#define ES_ejs_io_Path_copy_options                                    1
#define ES_ejs_io_Path_endsWith_suffix                                 0
#define ES_ejs_io_Path_find_glob                                       0
#define ES_ejs_io_Path_find_recurse                                    1
#define ES_ejs_io_Path_find_recursiveFind                              2
#define ES_ejs_io_Path_files_enumDirs                                  0
#define ES_ejs_io_Path_join_other                                      0
#define ES_ejs_io_Path_joinExt_ext                                     0
#define ES_ejs_io_Path_makeDir_options                                 0
#define ES_ejs_io_Path_makeLink_existing                               0
#define ES_ejs_io_Path_makeLink_hard                                   1
#define ES_ejs_io_Path_map_separator                                   0
#define ES_ejs_io_Path_open_options                                    0
#define ES_ejs_io_Path_openTextStream_options                          0
#define ES_ejs_io_Path_openBinaryStream_options                        0
#define ES_ejs_io_Path_set_perms_perms                                 0
#define ES_ejs_io_Path_readBytes_file                                  0
#define ES_ejs_io_Path_readLines_stream                                0
#define ES_ejs_io_Path_readString_file                                 0
#define ES_ejs_io_Path_readXML_file                                    0
#define ES_ejs_io_Path_readXML_data                                    1
#define ES_ejs_io_Path_removeAll__hoisted_0_f                          0
#define ES_ejs_io_Path_rename_target                                   0
#define ES_ejs_io_Path_replaceExt_ext                                  0
#define ES_ejs_io_Path_resolve_otherPaths                              0
#define ES_ejs_io_Path_same_other                                      0
#define ES_ejs_io_Path_startsWith_prefix                               0
#define ES_ejs_io_Path_trimEnd_pat                                     0
#define ES_ejs_io_Path_trimStart_pat                                   0
#define ES_ejs_io_Path_truncate_size                                   0
#define ES_ejs_io_Path_write_args                                      0
#define ES_ejs_io_Path_write_file                                      1
#define ES_ejs_io_Path_write__hoisted_2_item                           2
#define ES_ejs_io_Path_write__hoisted_3_es                             3


/**
 *   Class property slots for the "TextStream" class 
 */
#define ES_ejs_io_TextStream__origin                                   6
#define ES_ejs_io_TextStream_TextStream                                6
#define ES_ejs_io_TextStream__initializer__TextStream_initializer      7
#define ES_ejs_io_TextStream_LATIN1                                    8
#define ES_ejs_io_TextStream_UTF_8                                     9
#define ES_ejs_io_TextStream_UTF_16                                    10
#define ES_ejs_io_TextStream_available                                 11
#define ES_ejs_io_TextStream_close                                     12
#define ES_ejs_io_TextStream_encoding                                  13
#define ES_ejs_io_TextStream_set_encoding                              14
#define ES_ejs_io_TextStream_fill                                      15
#define ES_ejs_io_TextStream_flush                                     16
#define ES_ejs_io_TextStream_read                                      17
#define ES_ejs_io_TextStream_readLine                                  18
#define ES_ejs_io_TextStream_readLines                                 19
#define ES_ejs_io_TextStream_readString                                20
#define ES_ejs_io_TextStream_write                                     21
#define ES_ejs_io_TextStream_writeLine                                 22
#define ES_ejs_io_TextStream_NUM_CLASS_PROP                            23

/**
 * Instance slots for "TextStream" type 
 */
#define ES_ejs_io_TextStream_newline                                   0
#define ES_ejs_io_TextStream_inbuf                                     1
#define ES_ejs_io_TextStream_format                                    2
#define ES_ejs_io_TextStream_nextStream                                3
#define ES_ejs_io_TextStream_NUM_INSTANCE_PROP                         4

/**
 * 
 *    Local slots for methods in type TextStream 
 */
#define ES_ejs_io_TextStream_TextStream_stream                         0
#define ES_ejs_io_TextStream_close_graceful                            0
#define ES_ejs_io_TextStream_set_encoding_encoding                     0
#define ES_ejs_io_TextStream_flush_graceful                            0
#define ES_ejs_io_TextStream_read_buffer                               0
#define ES_ejs_io_TextStream_read_offset                               1
#define ES_ejs_io_TextStream_read_count                                2
#define ES_ejs_io_TextStream_read_total                                3
#define ES_ejs_io_TextStream_read_where                                4
#define ES_ejs_io_TextStream_read__hoisted_5_len                       5
#define ES_ejs_io_TextStream_readLine_nl                               0
#define ES_ejs_io_TextStream_readLine__hoisted_1_nlchar                1
#define ES_ejs_io_TextStream_readLine__hoisted_2_i                     2
#define ES_ejs_io_TextStream_readLines_numLines                        0
#define ES_ejs_io_TextStream_readLines_result                          1
#define ES_ejs_io_TextStream_readLines__hoisted_2_i                    2
#define ES_ejs_io_TextStream_readString_count                          0
#define ES_ejs_io_TextStream_write_data                                0
#define ES_ejs_io_TextStream_writeLine_lines                           0
#define ES_ejs_io_TextStream_writeLine_written                         1
#define ES_ejs_io_TextStream_writeLine_count                           2
#define ES_ejs_io_TextStream_writeLine__hoisted_3_line                 3


/**
 *   Class property slots for the "XMLHttp" class 
 */
#define ES_ejs_io_XMLHttp__origin                                      6
#define ES_ejs_io_XMLHttp_XMLHttp                                      6
#define ES_ejs_io_XMLHttp__initializer__XMLHttp_initializer            7
#define ES_ejs_io_XMLHttp_Uninitialized                                8
#define ES_ejs_io_XMLHttp_Open                                         9
#define ES_ejs_io_XMLHttp_Sent                                         10
#define ES_ejs_io_XMLHttp_Receiving                                    11
#define ES_ejs_io_XMLHttp_Loaded                                       12
#define ES_ejs_io_XMLHttp_abort                                        13
#define ES_ejs_io_XMLHttp_http                                         14
#define ES_ejs_io_XMLHttp_readyState                                   15
#define ES_ejs_io_XMLHttp_responseText                                 16
#define ES_ejs_io_XMLHttp_responseXML                                  17
#define ES_ejs_io_XMLHttp_responseBody                                 18
#define ES_ejs_io_XMLHttp_status                                       19
#define ES_ejs_io_XMLHttp_statusText                                   20
#define ES_ejs_io_XMLHttp_getAllResponseHeaders                        21
#define ES_ejs_io_XMLHttp_getResponseHeader                            22
#define ES_ejs_io_XMLHttp_open                                         23
#define ES_ejs_io_XMLHttp_send                                         24
#define ES_ejs_io_XMLHttp_setRequestHeader                             25
#define ES_ejs_io_XMLHttp_callback                                     26
#define ES_ejs_io_XMLHttp_notify                                       27
#define ES_ejs_io_XMLHttp_NUM_CLASS_PROP                               28

/**
 * Instance slots for "XMLHttp" type 
 */
#define ES_ejs_io_XMLHttp_hp                                           0
#define ES_ejs_io_XMLHttp_state                                        1
#define ES_ejs_io_XMLHttp_response                                     2
#define ES_ejs_io_XMLHttp_onreadystatechange                           3
#define ES_ejs_io_XMLHttp_NUM_INSTANCE_PROP                            4

/**
 * 
 *    Local slots for methods in type XMLHttp 
 */
#define ES_ejs_io_XMLHttp_getAllResponseHeaders_result                 0
#define ES_ejs_io_XMLHttp_getAllResponseHeaders__hoisted_1_key         1
#define ES_ejs_io_XMLHttp_getResponseHeader_key                        0
#define ES_ejs_io_XMLHttp_open_method                                  0
#define ES_ejs_io_XMLHttp_open_url                                     1
#define ES_ejs_io_XMLHttp_open_async                                   2
#define ES_ejs_io_XMLHttp_open_user                                    3
#define ES_ejs_io_XMLHttp_open_password                                4
#define ES_ejs_io_XMLHttp_open__hoisted_5_timeout                      5
#define ES_ejs_io_XMLHttp_open__hoisted_6_when                         6
#define ES_ejs_io_XMLHttp_send_content                                 0
#define ES_ejs_io_XMLHttp_setRequestHeader_key                         0
#define ES_ejs_io_XMLHttp_setRequestHeader_value                       1
#define ES_ejs_io_XMLHttp_callback_e                                   0
#define ES_ejs_io_XMLHttp_callback_hp                                  1
#define ES_ejs_io_XMLHttp_callback_count                               2

#define _ES_CHECKSUM_ejs_io 354597

#endif
