#
#	Makefile for the Ejscript web framework gatways and embeddings
#
#	Copyright (c) Embedthis Software LLC, 2003-2010. All Rights Reserved.
#
include 		.makedep

MAKE_IFLAGS		+=	$(BLD_APPWEB_IFLAGS)
