#
#	Makefile for the Ejscript web framework gatways and embeddings
#
#	Copyright (c) Embedthis Software LLC, 2003-2011. All Rights Reserved.
#
include 		.makedep

MAKE_IFLAGS		+=	$(BLD_APPWEB_IFLAGS)

#
#   Local variables:
#   tab-width: 4
#   c-basic-offset: 4
#   End:
#   vim: sw=4 ts=4
#
