#!/bin/sh
# 	prerm -- Pre removal script for Ejscript
#
#	Copyright (c) Embedthis Software LLC, 2003-2010. All Rights Reserved.
#

BLD_PRODUCT=!!BLD_PRODUCT!!
BLD_NAME="!!BLD_NAME!!"
BLD_BIN_PREFIX=!!ORIG_BLD_BIN_PREFIX!!
BLD_CFG_PREFIX=!!ORIG_BLD_CFG_PREFIX!!

###############################################################################
#
#	Main
#
cd /
action=$1
case $action in
	remove)					# when new
        "$BLD_BIN_PREFIX/linkup" Remove /
		;;
	upgrade)				# when old
        "$BLD_BIN_PREFIX/linkup" Remove /
		;;
	failed-upgrade)			# when new
		oldVersion=$2
		;;
	deconfigure)			# when old
		# 	deconfigure in-favor package-being-installed version removing 
		#	conflicting-package version
esac
exit 0
