#
#	Makefile to build the Ejscript core system classes
#
#	Copyright (c) Embedthis Software LLC, 2003-2011. All Rights Reserved.
#

include 		.makedep

ifeq			($(BLD_FEATURE_DECIMAL),1)
POST_DIRS		+= decimal
endif


x:
	echo dpath $(_DPATH_)

#
#   Local variables:
#   tab-width: 4
#   c-basic-offset: 4
#   End:
#   vim: sw=4 ts=4 noexpandtab
#
