#
#	Makefile to build the Ejscript types
#
#	Copyright (c) Embedthis Software LLC, 2003-2011. All Rights Reserved.
#

PRE_DIRS	:= core events io sys xml

include 	.makedep

#
#   Local variables:
#   tab-width: 4
#   c-basic-offset: 4
#   End:
#   vim: sw=4 ts=4 noexpandtab
#
