#
#	Makefile to build the samples
#
#	Copyright (c) Embedthis Software LLC, 2003-2011. All Rights Reserved.
#

include 	.makedep

ifeq ($(BLD_FEATURE_SAMPLES),1)
	PRE_DIRS	:= c
endif


#
#   Local variables:
#   tab-width: 4
#   c-basic-offset: 4
#   End:
#   vim: sw=4 ts=4 noexpandtab
#
