#!/bin/bash
#
#	postflight -- Post flight script for documentation
#	Copyright (c) Embedthis Software LLC, 2003-2011. All Rights Reserved.
#
###############################################################################

PKG_DIR="$1"
INS_DIR="$2"
NAME="!!BLD_DOC_PREFIX!!"
BIN="!!ORIG_BLD_BIN_PREFIX!!"
path="${INS_DIR}${NAME}"

${BIN}/linkup Install

if [ -f "$path/index.html" ] ; then
	open "$path/index.html"
fi
exit 0
