/*
 * ejs.unix.slots.h -- Property slot definitions for the "ejs.unix" module
 *
 * This file is generated by ec
 *
 * Slot definitions. Version 1.1.0.
 */

#ifndef _h_SLOTS_EjsUnixSlots
#define _h_SLOTS_EjsUnixSlots 1


/**
 * Slots for the "ejs.unix" module 
 */


/**
 *   Class property slots for the "global" class 
 */

/**
 * Instance slots for "global" type 
 */

/**
 * 
 *    Local slots for methods in type global 
 */

#define _ES_CHECKSUM_ejs_unix 820

#endif
