/*
 * ejs.sys.slots.h -- Property slot definitions for the "ejs.sys" module
 *
 * This file is generated by ec
 *
 * Slot definitions. Version 1.1.2.
 */

#ifndef _h_SLOTS_EjsSysSlots
#define _h_SLOTS_EjsSysSlots 1


/**
 * Slots for the "ejs.sys" module 
 */


/**
 *   Class property slots for the "global" class 
 */

/**
 * Instance slots for "global" type 
 */

/**
 * 
 *    Local slots for methods in type global 
 */


/**
 *   Class property slots for the "App" class 
 */
#define ES_ejs_sys_App__origin                                         6
#define ES_ejs_sys_App_args                                            6
#define ES_ejs_sys_App_dir                                             7
#define ES_ejs_sys_App_chdir                                           8
#define ES_ejs_sys_App_exeDir                                          9
#define ES_ejs_sys_App_exePath                                         10
#define ES_ejs_sys_App_errorStream                                     11
#define ES_ejs_sys_App_exit                                            12
#define ES_ejs_sys_App_getenv                                          13
#define ES_ejs_sys_App_inputStream                                     14
#define ES_ejs_sys_App_name                                            15
#define ES_ejs_sys_App_noexit                                          16
#define ES_ejs_sys_App_outputStream                                    17
#define ES_ejs_sys_App_putenv                                          18
#define ES_ejs_sys_App_searchPath                                      19
#define ES_ejs_sys_App_set_searchPath                                  20
#define ES_ejs_sys_App_serviceEvents                                   21
#define ES_ejs_sys_App_sleep                                           22
#define ES_ejs_sys_App_title                                           23
#define ES_ejs_sys_App_version                                         24
#define ES_ejs_sys_App_NUM_CLASS_PROP                                  25

/**
 * Instance slots for "App" type 
 */
#define ES_ejs_sys_App_NUM_INSTANCE_PROP                               0

/**
 * 
 *    Local slots for methods in type App 
 */
#define ES_ejs_sys_App_chdir_value                                     0
#define ES_ejs_sys_App_exit_status                                     0
#define ES_ejs_sys_App_getenv_name                                     0
#define ES_ejs_sys_App_noexit_exit                                     0
#define ES_ejs_sys_App_putenv_name                                     0
#define ES_ejs_sys_App_putenv_value                                    1
#define ES_ejs_sys_App_set_searchPath_path                             0
#define ES_ejs_sys_App_serviceEvents_count                             0
#define ES_ejs_sys_App_serviceEvents_timeout                           1
#define ES_ejs_sys_App_sleep_delay                                     0


/**
 *   Class property slots for the "Cmd" class 
 */
#define ES_ejs_sys_Cmd__origin                                         6
#define ES_ejs_sys_Cmd_locate                                          6
#define ES_ejs_sys_Cmd_sh                                              7
#define ES_ejs_sys_Cmd_run                                             8
#define ES_ejs_sys_Cmd_daemon                                          9
#define ES_ejs_sys_Cmd_runx                                            10
#define ES_ejs_sys_Cmd_NUM_CLASS_PROP                                  11

/**
 * Instance slots for "Cmd" type 
 */
#define ES_ejs_sys_Cmd_NUM_INSTANCE_PROP                               0

/**
 * 
 *    Local slots for methods in type Cmd 
 */
#define ES_ejs_sys_Cmd_locate_program                                  0
#define ES_ejs_sys_Cmd_locate_sep                                      1
#define ES_ejs_sys_Cmd_locate__hoisted_2_dir                           2
#define ES_ejs_sys_Cmd_locate__hoisted_3_path                          3
#define ES_ejs_sys_Cmd_locate__hoisted_4_ext                           4
#define ES_ejs_sys_Cmd_sh_cmdline                                      0
#define ES_ejs_sys_Cmd_sh_data                                         1
#define ES_ejs_sys_Cmd_sh_sh                                           2
#define ES_ejs_sys_Cmd_run_cmdline                                     0
#define ES_ejs_sys_Cmd_run_data                                        1
#define ES_ejs_sys_Cmd_daemon_cmdline                                  0
#define ES_ejs_sys_Cmd_runx_cmdline                                    0


/**
 *   Class property slots for the "Config" class 
 */
#define ES_ejs_sys_Config__origin                                      6
#define ES_ejs_sys_Config__initializer__Config_initializer             6
#define ES_ejs_sys_Config_Debug                                        7
#define ES_ejs_sys_Config_CPU                                          8
#define ES_ejs_sys_Config_DB                                           9
#define ES_ejs_sys_Config_E4X                                          10
#define ES_ejs_sys_Config_Floating                                     11
#define ES_ejs_sys_Config_Http                                         12
#define ES_ejs_sys_Config_Lang                                         13
#define ES_ejs_sys_Config_Legacy                                       14
#define ES_ejs_sys_Config_Multithread                                  15
#define ES_ejs_sys_Config_NumberType                                   16
#define ES_ejs_sys_Config_OS                                           17
#define ES_ejs_sys_Config_Product                                      18
#define ES_ejs_sys_Config_RegularExpressions                           19
#define ES_ejs_sys_Config_Title                                        20
#define ES_ejs_sys_Config_Version                                      21
#define ES_ejs_sys_Config_LibDir                                       22
#define ES_ejs_sys_Config_BinDir                                       23
#define ES_ejs_sys_Config_ModDir                                       24
#define ES_ejs_sys_Config_NUM_CLASS_PROP                               25

/**
 * Instance slots for "Config" type 
 */
#define ES_ejs_sys_Config_NUM_INSTANCE_PROP                            0


/**
 *   Class property slots for the "GC" class 
 */
#define ES_ejs_sys_GC__origin                                          6
#define ES_ejs_sys_GC_enabled                                          6
#define ES_ejs_sys_GC_set_enabled                                      7
#define ES_ejs_sys_GC_workQuota                                        8
#define ES_ejs_sys_GC_set_workQuota                                    9
#define ES_ejs_sys_GC_run                                              10
#define ES_ejs_sys_GC_NUM_CLASS_PROP                                   11

/**
 * Instance slots for "GC" type 
 */
#define ES_ejs_sys_GC_NUM_INSTANCE_PROP                                0

/**
 * 
 *    Local slots for methods in type GC 
 */
#define ES_ejs_sys_GC_set_enabled_on                                   0
#define ES_ejs_sys_GC_set_workQuota_quota                              0
#define ES_ejs_sys_GC_run_deep                                         0


/**
 *   Class property slots for the "Memory" class 
 */
#define ES_ejs_sys_Memory__origin                                      6
#define ES_ejs_sys_Memory_allocated                                    6
#define ES_ejs_sys_Memory_set_callback                                 7
#define ES_ejs_sys_Memory_callback                                     8
#define ES_ejs_sys_Memory_maximum                                      9
#define ES_ejs_sys_Memory_set_maximum                                  10
#define ES_ejs_sys_Memory_peak                                         11
#define ES_ejs_sys_Memory_redline                                      12
#define ES_ejs_sys_Memory_set_redline                                  13
#define ES_ejs_sys_Memory_resident                                     14
#define ES_ejs_sys_Memory_stack                                        15
#define ES_ejs_sys_Memory_system                                       16
#define ES_ejs_sys_Memory_stats                                        17
#define ES_ejs_sys_Memory_NUM_CLASS_PROP                               18

/**
 * Instance slots for "Memory" type 
 */
#define ES_ejs_sys_Memory_NUM_INSTANCE_PROP                            0

/**
 * 
 *    Local slots for methods in type Memory 
 */
#define ES_ejs_sys_Memory_set_callback_fn                              0
#define ES_ejs_sys_Memory_set_maximum_value                            0
#define ES_ejs_sys_Memory_set_redline_value                            0


/**
 *   Class property slots for the "System" class 
 */
#define ES_ejs_sys_System__origin                                      6
#define ES_ejs_sys_System__initializer__System_initializer             6
#define ES_ejs_sys_System_Bufsize                                      7
#define ES_ejs_sys_System_hostname                                     8
#define ES_ejs_sys_System_run                                          9
#define ES_ejs_sys_System_runx                                         10
#define ES_ejs_sys_System_daemon                                       11
#define ES_ejs_sys_System_sh                                           12
#define ES_ejs_sys_System_cmd                                          13
#define ES_ejs_sys_System_exec                                         14
#define ES_ejs_sys_System_NUM_CLASS_PROP                               15

/**
 * Instance slots for "System" type 
 */
#define ES_ejs_sys_System_NUM_INSTANCE_PROP                            0

/**
 * 
 *    Local slots for methods in type System 
 */
#define ES_ejs_sys_System_run_cmd                                      0
#define ES_ejs_sys_System_runx_cmd                                     0
#define ES_ejs_sys_System_daemon_cmd                                   0
#define ES_ejs_sys_System_sh_args                                      0
#define ES_ejs_sys_System_sh_sh                                        1
#define ES_ejs_sys_System_cmd_args                                     0
#define ES_ejs_sys_System_exec_args                                    0


/**
 *   Class property slots for the "Worker" class 
 */
#define ES_ejs_sys_Worker__origin                                      6
#define ES_ejs_sys_Worker_Worker                                       6
#define ES_ejs_sys_Worker_eval                                         7
#define ES_ejs_sys_Worker_exit                                         8
#define ES_ejs_sys_Worker_join                                         9
#define ES_ejs_sys_Worker_load                                         10
#define ES_ejs_sys_Worker_preload                                      11
#define ES_ejs_sys_Worker_lookup                                       12
#define ES_ejs_sys_Worker_postMessage                                  13
#define ES_ejs_sys_Worker_terminate                                    14
#define ES_ejs_sys_Worker_waitForMessage                               15
#define ES_ejs_sys_Worker_NUM_CLASS_PROP                               16

/**
 * Instance slots for "Worker" type 
 */
#define ES_ejs_sys_Worker_onclose                                      0
#define ES_ejs_sys_Worker_onmessage                                    1
#define ES_ejs_sys_Worker_onerror                                      2
#define ES_ejs_sys_Worker_name                                         3
#define ES_ejs_sys_Worker_NUM_INSTANCE_PROP                            4

/**
 * 
 *    Local slots for methods in type Worker 
 */
#define ES_ejs_sys_Worker_Worker_script                                0
#define ES_ejs_sys_Worker_Worker_options                               1
#define ES_ejs_sys_Worker_eval_script                                  0
#define ES_ejs_sys_Worker_eval_timeout                                 1
#define ES_ejs_sys_Worker_join_workers                                 0
#define ES_ejs_sys_Worker_join_timeout                                 1
#define ES_ejs_sys_Worker_load_script                                  0
#define ES_ejs_sys_Worker_load_timeout                                 1
#define ES_ejs_sys_Worker_preload_path                                 0
#define ES_ejs_sys_Worker_lookup_name                                  0
#define ES_ejs_sys_Worker_postMessage_data                             0
#define ES_ejs_sys_Worker_postMessage_ports                            1
#define ES_ejs_sys_Worker_waitForMessage_timeout                       0

#define _ES_CHECKSUM_ejs_sys 138148

#endif
