/*
 * ejs.slots.h -- Property slot definitions for the "ejs" module
 *
 * This file is generated by ec
 *
 * Slot definitions. Version 1.0.2.
 */

#ifndef _h_SLOTS_EjsSlots
#define _h_SLOTS_EjsSlots 1


/**
 * Slots for the "ejs" module 
 */


/**
 *   Class property slots for the "global" class 
 */
#define ES_Object                                                      0
#define ES_Boolean                                                     1
#define ES_Null                                                        2
#define ES_Number                                                      3
#define ES_String                                                      4
#define ES_Void                                                        5
#define ES_Frame                                                       6
#define ES_Function                                                    7
#define ES_makeGetter                                                  8
#define ES_clearBoundThis                                              9
#define ES_Array                                                       10
#define ES_Block                                                       11
#define ES_ByteArray                                                   12
#define ES_Date                                                        13
#define ES_ArgError                                                    14
#define ES_ArithmeticError                                             15
#define ES_AssertError                                                 16
#define ES_InstructionError                                            17
#define ES_Error                                                       18
#define ES_IOError                                                     19
#define ES_InternalError                                               20
#define ES_MemoryError                                                 21
#define ES_OutOfBoundsError                                            22
#define ES_ReferenceError                                              23
#define ES_ResourceError                                               24
#define ES_StateError                                                  25
#define ES_SyntaxError                                                 26
#define ES_TypeError                                                   27
#define ES_URIError                                                    28
#define ES_Iterable                                                    29
#define ES_Iterator                                                    30
#define ES_JSON                                                        31
#define ES_Math                                                        32
#define ES_Namespace                                                   33
#define ES_Reflect                                                     34
#define ES_typeOf                                                      35
#define ES_RegExp                                                      36
#define ES_Stream                                                      37
#define ES_Type                                                        38
#define ES_ECMA                                                        39
#define ES_public                                                      40
#define ES_internal                                                    41
#define ES_intrinsic                                                   42
#define ES_iterator                                                    43
#define ES_CONFIG                                                      44
#define ES_TODO                                                        45
#define ES_FUTURE                                                      46
#define ES_ASC                                                         47
#define ES_DOC_ONLY                                                    48
#define ES_DEPRECATED                                                  49
#define ES_REGEXP                                                      50
#define ES_boolean                                                     51
#define ES_double                                                      52
#define ES_num                                                         53
#define ES_string                                                      54
#define ES_false                                                       55
#define ES_global                                                      56
#define ES_null                                                        57
#define ES_Infinity                                                    58
#define ES_NegativeInfinity                                            59
#define ES_NaN                                                         60
#define ES_StopIteration                                               61
#define ES_true                                                        62
#define ES_undefined                                                   63
#define ES_void                                                        64
#define ES_assert                                                      65
#define ES_breakpoint                                                  66
#define ES_cloneBase                                                   67
#define ES_deserialize                                                 68
#define ES_decodeURI                                                   69
#define ES_dump                                                        70
#define ES_error                                                       71
#define ES_escape                                                      72
#define ES_encodeURI                                                   73
#define ES_md5                                                         74
#define ES_eval                                                        75
#define ES_formatStack                                                 76
#define ES_hashcode                                                    77
#define ES_input                                                       78
#define ES_load                                                        79
#define ES_output                                                      80
#define ES_print                                                       81
#define ES_printv                                                      82
#define ES_parse                                                       83
#define ES_serialize                                                   84
#define ES_printHash                                                   85
#define ES_instanceOf                                                  86
#define ES_ejs_events_Event                                            87
#define ES_ejs_events_ErrorEvent                                       88
#define ES_ejs_events_Dispatcher                                       89
#define ES_Endpoint                                                    90
#define ES_ejs_events_Timer                                            91
#define ES_ejs_events_TimerEvent                                       92
#define ES_XML                                                         93
#define ES_XMLList                                                     94
#define ES_ejs_io_BinaryStream                                         95
#define ES_ejs_io_File                                                 96
#define ES_ejs_io_FileSystem                                           97
#define ES_ejs_io_Http                                                 98
#define ES_ejs_io_HttpDataEvent                                        99
#define ES_ejs_io_HttpErrorEvent                                       100
#define ES_ejs_io_Path                                                 101
#define ES_ejs_io_TextStream                                           102
#define ES_ejs_io_XMLHttp                                              103
#define ES_ejs_sys_App                                                 104
#define ES_ejs_sys_Cmd                                                 105
#define ES_gc                                                          106
#define ES_readFile                                                    107
#define ES_ejs_sys_Config                                              108
#define ES_ejs_sys_GC                                                  109
#define ES_ejs_sys_Memory                                              110
#define ES_ejs_sys_System                                              111
#define ES_basename                                                    112
#define ES_chdir                                                       113
#define ES_chmod                                                       114
#define ES_close                                                       115
#define ES_cp                                                          116
#define ES_dirname                                                     117
#define ES_exists                                                      118
#define ES_extension                                                   119
#define ES_isDir                                                       120
#define ES_kill                                                        121
#define ES_ls                                                          122
#define ES_find                                                        123
#define ES_mkdir                                                       124
#define ES_mv                                                          125
#define ES_open                                                        126
#define ES_pwd                                                         127
#define ES_read                                                        128
#define ES_rm                                                          129
#define ES_rmdir                                                       130
#define ES_tempname                                                    131
#define ES_write                                                       132
#define ES_ejs_sys_Worker                                              133
#define ES_ejs_sys_worker_self                                         134
#define ES_ejs_sys_worker_exit                                         135
#define ES_ejs_sys_worker_postMessage                                  136
#define ES_ejs_sys_worker_onerror                                      137
#define ES_ejs_sys_worker_set_onerror                                  138
#define ES_ejs_sys_worker_onmessage                                    139
#define ES_ejs_sys_worker_set_onmessage                                140
#define ES_global_NUM_CLASS_PROP                                       141

/**
 * Instance slots for "global" type 
 */
#define ES_global_NUM_INSTANCE_PROP                                    0

/**
 * 
 *    Local slots for methods in type global 
 */
#define ES_makeGetter_fn                                               0
#define ES_clearBoundThis_fn                                           0
#define ES_typeOf_o                                                    0
#define ES_assert_condition                                            0
#define ES_cloneBase_klass                                             0
#define ES_deserialize_obj                                             0
#define ES_decodeURI_str                                               0
#define ES_dump_args                                                   0
#define ES_dump_e                                                      1
#define ES_error_args                                                  0
#define ES_escape_str                                                  0
#define ES_encodeURI_str                                               0
#define ES_md5_str                                                     0
#define ES_eval_script                                                 0
#define ES_hashcode_o                                                  0
#define ES_load_file                                                   0
#define ES_output_args                                                 0
#define ES_print_args                                                  0
#define ES_printv_args                                                 0
#define ES_parse_str                                                   0
#define ES_parse_preferredType                                         1
#define ES_serialize_obj                                               0
#define ES_serialize_maxDepth                                          1
#define ES_serialize_all                                               2
#define ES_serialize_base                                              3
#define ES_printHash_name                                              0
#define ES_printHash_o                                                 1
#define ES_instanceOf_obj                                              0
#define ES_instanceOf_target                                           1
#define ES_readFile_path                                               0
#define ES_readFile_encoding                                           1
#define ES_basename_path                                               0
#define ES_chdir_dir                                                   0
#define ES_chmod_path                                                  0
#define ES_chmod_perms                                                 1
#define ES_close_file                                                  0
#define ES_close_graceful                                              1
#define ES_cp_fromPath                                                 0
#define ES_cp_toPath                                                   1
#define ES_dirname_path                                                0
#define ES_exists_path                                                 0
#define ES_extension_path                                              0
#define ES_isDir_path                                                  0
#define ES_kill_pid                                                    0
#define ES_kill_signal                                                 1
#define ES_ls_path                                                     0
#define ES_ls_enumDirs                                                 1
#define ES_find_path                                                   0
#define ES_find_glob                                                   1
#define ES_find_recurse                                                2
#define ES_find_result                                                 3
#define ES_find__hoisted_4_paths                                       4
#define ES_find__hoisted_5_path                                        5
#define ES_mkdir_path                                                  0
#define ES_mkdir_permissions                                           1
#define ES_mv_fromFile                                                 0
#define ES_mv_toFile                                                   1
#define ES_open_path                                                   0
#define ES_open_mode                                                   1
#define ES_open_permissions                                            2
#define ES_read_file                                                   0
#define ES_read_count                                                  1
#define ES_rm_path                                                     0
#define ES_rmdir_path                                                  0
#define ES_rmdir_contents                                              1
#define ES_tempname_directory                                          0
#define ES_write_file                                                  0
#define ES_write_items                                                 1
#define ES_ejs_sys_worker_postMessage_data                             0
#define ES_ejs_sys_worker_set_onerror_fun                              0
#define ES_ejs_sys_worker_set_onmessage_fun                            0


/**
 *   Class property slots for the "Object" class 
 */
#define ES_Object__origin                                              0
#define ES_Object_clone                                                0
#define ES_Object_get                                                  1
#define ES_Object_getValues                                            2
#define ES_Object_length                                               3
#define ES_Object_toJSON                                               4
#define ES_Object_toString                                             5
#define ES_Object_NUM_CLASS_PROP                                       6

/**
 * Instance slots for "Object" type 
 */
#define ES_Object_NUM_INSTANCE_PROP                                    0

/**
 * 
 *    Local slots for methods in type Object 
 */
#define ES_Object_clone_deep                                           0


/**
 *   Class property slots for the "Boolean" class 
 */
#define ES_Boolean__origin                                             6
#define ES_Boolean_Boolean                                             6
#define ES_Boolean_NUM_CLASS_PROP                                      7

/**
 * Instance slots for "Boolean" type 
 */
#define ES_Boolean_NUM_INSTANCE_PROP                                   0

/**
 * 
 *    Local slots for methods in type Boolean 
 */
#define ES_Boolean_Boolean_value                                       0


/**
 *   Class property slots for the "Null" class 
 */
#define ES_Null__origin                                                6
#define ES_Null_NUM_CLASS_PROP                                         6

/**
 * Instance slots for "Null" type 
 */
#define ES_Null_NUM_INSTANCE_PROP                                      0


/**
 *   Class property slots for the "Number" class 
 */
#define ES_Number__origin                                              6
#define ES_Number_Number                                               6
#define ES_Number__initializer__Number_initializer                     7
#define ES_Number_MAX_VALUE                                            8
#define ES_Number_MIN_VALUE                                            9
#define ES_Number_NaN                                                  10
#define ES_Number_NEGATIVE_INFINITY                                    11
#define ES_Number_POSITIVE_INFINITY                                    12
#define ES_Number_MaxValue                                             13
#define ES_Number_MinValue                                             14
#define ES_Number_abs                                                  15
#define ES_Number_ceil                                                 16
#define ES_Number_floor                                                17
#define ES_Number_isFinite                                             18
#define ES_Number_isNaN                                                19
#define ES_Number_round                                                20
#define ES_Number_toExponential                                        21
#define ES_Number_toFixed                                              22
#define ES_Number_toPrecision                                          23
#define ES_Number_byte                                                 24
#define ES_Number_integral                                             25
#define ES_Number_max                                                  26
#define ES_Number_min                                                  27
#define ES_Number_power                                                28
#define ES_Number_NUM_CLASS_PROP                                       29

/**
 * Instance slots for "Number" type 
 */
#define ES_Number_NUM_INSTANCE_PROP                                    0

/**
 * 
 *    Local slots for methods in type Number 
 */
#define ES_Number_Number_value                                         0
#define ES_Number_toExponential_fractionDigits                         0
#define ES_Number_toFixed_fractionDigits                               0
#define ES_Number_toPrecision_numDigits                                0
#define ES_Number_integral_size                                        0
#define ES_Number_max_other                                            0
#define ES_Number_max_result                                           1
#define ES_Number_max__hoisted_2_n                                     2
#define ES_Number_min_other                                            0
#define ES_Number_min_result                                           1
#define ES_Number_min__hoisted_2_n                                     2
#define ES_Number_power_nth                                            0


/**
 *   Class property slots for the "String" class 
 */
#define ES_String__origin                                              6
#define ES_String_String                                               6
#define ES_String_caseCompare                                          7
#define ES_String_charAt                                               8
#define ES_String_charCodeAt                                           9
#define ES_String_concat                                               10
#define ES_String_contains                                             11
#define ES_String_endsWith                                             12
#define ES_String_format                                               13
#define ES_String_fromCharCode                                         14
#define ES_String_indexOf                                              15
#define ES_String_isDigit                                              16
#define ES_String_isAlpha                                              17
#define ES_String_isLower                                              18
#define ES_String_isSpace                                              19
#define ES_String_isUpper                                              20
#define ES_String_lastIndexOf                                          21
#define ES_String_match                                                22
#define ES_String_parseJSON                                            23
#define ES_String_toCamel                                              24
#define ES_String_toPascal                                             25
#define ES_String_printable                                            26
#define ES_String_quote                                                27
#define ES_String_remove                                               28
#define ES_String_replace                                              29
#define ES_String_reverse                                              30
#define ES_String_search                                               31
#define ES_String_slice                                                32
#define ES_String_split                                                33
#define ES_String_startsWith                                           34
#define ES_String_substring                                            35
#define ES_String_times                                                36
#define ES_String_tokenize                                             37
#define ES_String_toLower                                              38
#define ES_String_toUpper                                              39
#define ES_String_trim                                                 40
#define ES_String_MINUS                                                41
#define ES_String_MOD                                                  42
#define ES_String_NUM_CLASS_PROP                                       43

/**
 * Instance slots for "String" type 
 */
#define ES_String_NUM_INSTANCE_PROP                                    0

/**
 * 
 *    Local slots for methods in type String 
 */
#define ES_String_String_str                                           0
#define ES_String_caseCompare_compare                                  0
#define ES_String_charAt_index                                         0
#define ES_String_charCodeAt_index                                     0
#define ES_String_concat_args                                          0
#define ES_String_contains_pattern                                     0
#define ES_String_endsWith_test                                        0
#define ES_String_format_args                                          0
#define ES_String_fromCharCode_codes                                   0
#define ES_String_indexOf_pattern                                      0
#define ES_String_indexOf_startIndex                                   1
#define ES_String_lastIndexOf_pattern                                  0
#define ES_String_lastIndexOf_location                                 1
#define ES_String_match_pattern                                        0
#define ES_String_parseJSON_filter                                     0
#define ES_String_remove_start                                         0
#define ES_String_remove_end                                           1
#define ES_String_replace_pattern                                      0
#define ES_String_replace_replacement                                  1
#define ES_String_search_pattern                                       0
#define ES_String_slice_start                                          0
#define ES_String_slice_end                                            1
#define ES_String_slice_step                                           2
#define ES_String_split_delimiter                                      0
#define ES_String_split_limit                                          1
#define ES_String_startsWith_test                                      0
#define ES_String_substring_startIndex                                 0
#define ES_String_substring_end                                        1
#define ES_String_times_times                                          0
#define ES_String_times_s                                              1
#define ES_String_times__hoisted_2_i                                   2
#define ES_String_tokenize_format                                      0
#define ES_String_trim_str                                             0
#define ES_String_MINUS_str                                            0
#define ES_String_MINUS_i                                              1
#define ES_String_MOD_arg                                              0


/**
 *   Class property slots for the "Void" class 
 */
#define ES_Void__origin                                                6
#define ES_Void_NUM_CLASS_PROP                                         6

/**
 * Instance slots for "Void" type 
 */
#define ES_Void_NUM_INSTANCE_PROP                                      0


/**
 *   Class property slots for the "Function" class 
 */
#define ES_Function__origin                                            6
#define ES_Function_apply                                              6
#define ES_Function_call                                               7
#define ES_Function_NUM_CLASS_PROP                                     8

/**
 * Instance slots for "Function" type 
 */
#define ES_Function_NUM_INSTANCE_PROP                                  0

/**
 * 
 *    Local slots for methods in type Function 
 */
#define ES_Function_apply_thisObject                                   0
#define ES_Function_apply_args                                         1
#define ES_Function_call_thisObject                                    0
#define ES_Function_call_args                                          1


/**
 *   Class property slots for the "Array" class 
 */
#define ES_Array__origin                                               6
#define ES_Array_Array                                                 6
#define ES_Array_append                                                7
#define ES_Array_clear                                                 8
#define ES_Array_compact                                               9
#define ES_Array_concat                                                10
#define ES_Array_contains                                              11
#define ES_Array_every                                                 12
#define ES_Array_filter                                                13
#define ES_Array_find                                                  14
#define ES_Array_findAll                                               15
#define ES_Array_forEach                                               16
#define ES_Array_indexOf                                               17
#define ES_Array_insert                                                18
#define ES_Array_join                                                  19
#define ES_Array_lastIndexOf                                           20
#define ES_Array_set_length                                            21
#define ES_Array_map                                                   22
#define ES_Array_pop                                                   23
#define ES_Array_push                                                  24
#define ES_Array_reject                                                25
#define ES_Array_remove                                                26
#define ES_Array_reverse                                               27
#define ES_Array_shift                                                 28
#define ES_Array_slice                                                 29
#define ES_Array_some                                                  30
#define ES_Array_sort                                                  31
#define ES_Array_splice                                                32
#define ES_Array_transform                                             33
#define ES_Array_unique                                                34
#define ES_Array_unshift                                               35
#define ES_Array_NUM_CLASS_PROP                                        36

/**
 * Instance slots for "Array" type 
 */
#define ES_Array_NUM_INSTANCE_PROP                                     0

/**
 * 
 *    Local slots for methods in type Array 
 */
#define ES_Array_Array_values                                          0
#define ES_Array_append_obj                                            0
#define ES_Array_concat_args                                           0
#define ES_Array_contains_element                                      0
#define ES_Array_every_match                                           0
#define ES_Array_every__hoisted_1_i                                    1
#define ES_Array_filter_match                                          0
#define ES_Array_find_match                                            0
#define ES_Array_find_result                                           1
#define ES_Array_find__hoisted_2_i                                     2
#define ES_Array_findAll_match                                         0
#define ES_Array_findAll_result                                        1
#define ES_Array_findAll__hoisted_2_i                                  2
#define ES_Array_forEach_modifier                                      0
#define ES_Array_indexOf_element                                       0
#define ES_Array_indexOf_startIndex                                    1
#define ES_Array_insert_pos                                            0
#define ES_Array_insert_args                                           1
#define ES_Array_join_sep                                              0
#define ES_Array_lastIndexOf_element                                   0
#define ES_Array_lastIndexOf_startIndex                                1
#define ES_Array_set_length_value                                      0
#define ES_Array_map_mapper                                            0
#define ES_Array_map_result                                            1
#define ES_Array_push_items                                            0
#define ES_Array_reject_match                                          0
#define ES_Array_reject_result                                         1
#define ES_Array_reject__hoisted_2_i                                   2
#define ES_Array_remove_start                                          0
#define ES_Array_remove_end                                            1
#define ES_Array_slice_start                                           0
#define ES_Array_slice_end                                             1
#define ES_Array_slice_step                                            2
#define ES_Array_some_match                                            0
#define ES_Array_some_result                                           1
#define ES_Array_some__hoisted_2_i                                     2
#define ES_Array_sort_compare                                          0
#define ES_Array_sort_order                                            1
#define ES_Array_splice_start                                          0
#define ES_Array_splice_deleteCount                                    1
#define ES_Array_splice_values                                         2
#define ES_Array_transform_mapper                                      0
#define ES_Array_transform__hoisted_1_i                                1
#define ES_Array_unshift_items                                         0


/**
 *   Class property slots for the "Block" class 
 */
#define ES_Block__origin                                               6
#define ES_Block_NUM_CLASS_PROP                                        6

/**
 * Instance slots for "Block" type 
 */
#define ES_Block_NUM_INSTANCE_PROP                                     0


/**
 *   Class property slots for the "ByteArray" class 
 */
#define ES_ByteArray__origin                                           6
#define ES_ByteArray_ByteArray                                         6
#define ES_ByteArray__initializer__ByteArray_initializer               7
#define ES_ByteArray_LittleEndian                                      8
#define ES_ByteArray_BigEndian                                         9
#define ES_ByteArray_available                                         10
#define ES_ByteArray_close                                             11
#define ES_ByteArray_compact                                           12
#define ES_ByteArray_copyIn                                            13
#define ES_ByteArray_copyOut                                           14
#define ES_ByteArray_endian                                            15
#define ES_ByteArray_set_endian                                        16
#define ES_ByteArray_flush                                             17
#define ES_ByteArray_set_input                                         18
#define ES_ByteArray_input                                             19
#define ES_ByteArray_output                                            20
#define ES_ByteArray_set_output                                        21
#define ES_ByteArray_read                                              22
#define ES_ByteArray_readBoolean                                       23
#define ES_ByteArray_readByte                                          24
#define ES_ByteArray_readDate                                          25
#define ES_ByteArray_readDouble                                        26
#define ES_ByteArray_readInteger                                       27
#define ES_ByteArray_readLong                                          28
#define ES_ByteArray_readPosition                                      29
#define ES_ByteArray_set_readPosition                                  30
#define ES_ByteArray_readShort                                         31
#define ES_ByteArray_readString                                        32
#define ES_ByteArray_readXML                                           33
#define ES_ByteArray_reset                                             34
#define ES_ByteArray_room                                              35
#define ES_ByteArray_write                                             36
#define ES_ByteArray_writeByte                                         37
#define ES_ByteArray_writeShort                                        38
#define ES_ByteArray_writeDouble                                       39
#define ES_ByteArray_writeInteger                                      40
#define ES_ByteArray_writeLong                                         41
#define ES_ByteArray_writePosition                                     42
#define ES_ByteArray_set_writePosition                                 43
#define ES_ByteArray_NUM_CLASS_PROP                                    44

/**
 * Instance slots for "ByteArray" type 
 */
#define ES_ByteArray_NUM_INSTANCE_PROP                                 0

/**
 * 
 *    Local slots for methods in type ByteArray 
 */
#define ES_ByteArray_ByteArray_size                                    0
#define ES_ByteArray_ByteArray_growable                                1
#define ES_ByteArray_close_graceful                                    0
#define ES_ByteArray_copyIn_destOffset                                 0
#define ES_ByteArray_copyIn_src                                        1
#define ES_ByteArray_copyIn_srcOffset                                  2
#define ES_ByteArray_copyIn_count                                      3
#define ES_ByteArray_copyOut_srcOffset                                 0
#define ES_ByteArray_copyOut_dest                                      1
#define ES_ByteArray_copyOut_destOffset                                2
#define ES_ByteArray_copyOut_count                                     3
#define ES_ByteArray_set_endian_value                                  0
#define ES_ByteArray_flush_graceful                                    0
#define ES_ByteArray_set_input_callback                                0
#define ES_ByteArray_set_output_callback                               0
#define ES_ByteArray_read_buffer                                       0
#define ES_ByteArray_read_offset                                       1
#define ES_ByteArray_read_count                                        2
#define ES_ByteArray_set_readPosition_position                         0
#define ES_ByteArray_readString_count                                  0
#define ES_ByteArray_write_data                                        0
#define ES_ByteArray_writeByte_data                                    0
#define ES_ByteArray_writeShort_data                                   0
#define ES_ByteArray_writeDouble_data                                  0
#define ES_ByteArray_writeInteger_data                                 0
#define ES_ByteArray_writeLong_data                                    0
#define ES_ByteArray_set_writePosition_position                        0


/**
 *   Class property slots for the "Date" class 
 */
#define ES_Date__origin                                                6
#define ES_Date_Date                                                   6
#define ES_Date_day                                                    7
#define ES_Date_set_day                                                8
#define ES_Date_dayOfYear                                              9
#define ES_Date_set_dayOfYear                                          10
#define ES_Date_date                                                   11
#define ES_Date_set_date                                               12
#define ES_Date_elapsed                                                13
#define ES_Date_format                                                 14
#define ES_Date_formatUTC                                              15
#define ES_Date_fullYear                                               16
#define ES_Date_set_fullYear                                           17
#define ES_Date_getDate                                                18
#define ES_Date_getDay                                                 19
#define ES_Date_getFullYear                                            20
#define ES_Date_getHours                                               21
#define ES_Date_getMilliseconds                                        22
#define ES_Date_getMinutes                                             23
#define ES_Date_getMonth                                               24
#define ES_Date_getSeconds                                             25
#define ES_Date_getTime                                                26
#define ES_Date_getTimezoneOffset                                      27
#define ES_Date_getUTCDate                                             28
#define ES_Date_getUTCDay                                              29
#define ES_Date_getUTCFullYear                                         30
#define ES_Date_getUTCHours                                            31
#define ES_Date_getUTCMilliseconds                                     32
#define ES_Date_getUTCMinutes                                          33
#define ES_Date_getUTCMonth                                            34
#define ES_Date_getUTCSeconds                                          35
#define ES_Date_hours                                                  36
#define ES_Date_set_hours                                              37
#define ES_Date_milliseconds                                           38
#define ES_Date_set_milliseconds                                       39
#define ES_Date_minutes                                                40
#define ES_Date_set_minutes                                            41
#define ES_Date_month                                                  42
#define ES_Date_set_month                                              43
#define ES_Date_nanoAge                                                44
#define ES_Date_nextDay                                                45
#define ES_Date_now                                                    46
#define ES_Date_parseDate                                              47
#define ES_Date_parseUTCDate                                           48
#define ES_Date_parse                                                  49
#define ES_Date_seconds                                                50
#define ES_Date_set_seconds                                            51
#define ES_Date_setDate                                                52
#define ES_Date_setFullYear                                            53
#define ES_Date_setHours                                               54
#define ES_Date_setMilliseconds                                        55
#define ES_Date_setMinutes                                             56
#define ES_Date_setMonth                                               57
#define ES_Date_setSeconds                                             58
#define ES_Date_setTime                                                59
#define ES_Date_setUTCDate                                             60
#define ES_Date_setUTCFullYear                                         61
#define ES_Date_setUTCHours                                            62
#define ES_Date_setUTCMilliseconds                                     63
#define ES_Date_setUTCMinutes                                          64
#define ES_Date_setUTCMonth                                            65
#define ES_Date_setUTCSeconds                                          66
#define ES_Date_time                                                   67
#define ES_Date_set_time                                               68
#define ES_Date_toDateString                                           69
#define ES_Date_toISOString                                            70
#define ES_Date_toLocaleDateString                                     71
#define ES_Date_toLocaleString                                         72
#define ES_Date_toLocaleTimeString                                     73
#define ES_Date_toTimeString                                           74
#define ES_Date_toUTCString                                            75
#define ES_Date_UTC                                                    76
#define ES_Date_valueOf                                                77
#define ES_Date_year                                                   78
#define ES_Date_set_year                                               79
#define ES_Date_NUM_CLASS_PROP                                         80

/**
 * Instance slots for "Date" type 
 */
#define ES_Date_NUM_INSTANCE_PROP                                      0

/**
 * 
 *    Local slots for methods in type Date 
 */
#define ES_Date_Date_args                                              0
#define ES_Date_set_day_day                                            0
#define ES_Date_set_dayOfYear_day                                      0
#define ES_Date_set_date_date                                          0
#define ES_Date_format_layout                                          0
#define ES_Date_formatUTC_layout                                       0
#define ES_Date_set_fullYear_year                                      0
#define ES_Date_set_hours_hour                                         0
#define ES_Date_set_milliseconds_ms                                    0
#define ES_Date_set_minutes_min                                        0
#define ES_Date_set_month_month                                        0
#define ES_Date_nextDay_inc                                            0
#define ES_Date_parseDate_dateString                                   0
#define ES_Date_parseDate_defaultDate                                  1
#define ES_Date_parseUTCDate_dateString                                0
#define ES_Date_parseUTCDate_defaultDate                               1
#define ES_Date_parse_dateString                                       0
#define ES_Date_set_seconds_sec                                        0
#define ES_Date_setDate_d                                              0
#define ES_Date_setFullYear_y                                          0
#define ES_Date_setHours_h                                             0
#define ES_Date_setMilliseconds_ms                                     0
#define ES_Date_setMinutes_min                                         0
#define ES_Date_setMonth_mon                                           0
#define ES_Date_setSeconds_sec                                         0
#define ES_Date_setSeconds_msec                                        1
#define ES_Date_setTime_value                                          0
#define ES_Date_setUTCDate_d                                           0
#define ES_Date_setUTCFullYear_y                                       0
#define ES_Date_setUTCHours_h                                          0
#define ES_Date_setUTCMilliseconds_ms                                  0
#define ES_Date_setUTCMinutes_min                                      0
#define ES_Date_setUTCMonth_mon                                        0
#define ES_Date_setUTCSeconds_sec                                      0
#define ES_Date_setUTCSeconds_msec                                     1
#define ES_Date_set_time_value                                         0
#define ES_Date_UTC_year                                               0
#define ES_Date_UTC_month                                              1
#define ES_Date_UTC_day                                                2
#define ES_Date_UTC_hours                                              3
#define ES_Date_UTC_minutes                                            4
#define ES_Date_UTC_seconds                                            5
#define ES_Date_UTC_milliseconds                                       6
#define ES_Date_set_year_year                                          0


/**
 *   Class property slots for the "ArgError" class 
 */
#define ES_ArgError__origin                                            9
#define ES_ArgError_ArgError                                           9
#define ES_ArgError_NUM_CLASS_PROP                                     10

/**
 * Instance slots for "ArgError" type 
 */
#define ES_ArgError_NUM_INSTANCE_PROP                                  0

/**
 * 
 *    Local slots for methods in type ArgError 
 */
#define ES_ArgError_ArgError_message                                   0


/**
 *   Class property slots for the "ArithmeticError" class 
 */
#define ES_ArithmeticError__origin                                     9
#define ES_ArithmeticError_ArithmeticError                             9
#define ES_ArithmeticError_NUM_CLASS_PROP                              10

/**
 * Instance slots for "ArithmeticError" type 
 */
#define ES_ArithmeticError_NUM_INSTANCE_PROP                           0

/**
 * 
 *    Local slots for methods in type ArithmeticError 
 */
#define ES_ArithmeticError_ArithmeticError_message                     0


/**
 *   Class property slots for the "AssertError" class 
 */
#define ES_AssertError__origin                                         9
#define ES_AssertError_AssertError                                     9
#define ES_AssertError_NUM_CLASS_PROP                                  10

/**
 * Instance slots for "AssertError" type 
 */
#define ES_AssertError_NUM_INSTANCE_PROP                               0

/**
 * 
 *    Local slots for methods in type AssertError 
 */
#define ES_AssertError_AssertError_message                             0


/**
 *   Class property slots for the "InstructionError" class 
 */
#define ES_InstructionError__origin                                    9
#define ES_InstructionError_InstructionError                           9
#define ES_InstructionError_NUM_CLASS_PROP                             10

/**
 * Instance slots for "InstructionError" type 
 */
#define ES_InstructionError_NUM_INSTANCE_PROP                          0

/**
 * 
 *    Local slots for methods in type InstructionError 
 */
#define ES_InstructionError_InstructionError_message                   0


/**
 *   Class property slots for the "Error" class 
 */
#define ES_Error__origin                                               6
#define ES_Error_Error                                                 6
#define ES_Error_code                                                  7
#define ES_Error_set_code                                              8
#define ES_Error_NUM_CLASS_PROP                                        9

/**
 * Instance slots for "Error" type 
 */
#define ES_Error_message                                               0
#define ES_Error_stack                                                 1
#define ES_Error_NUM_INSTANCE_PROP                                     2

/**
 * 
 *    Local slots for methods in type Error 
 */
#define ES_Error_Error_message                                         0
#define ES_Error_set_code_value                                        0


/**
 *   Class property slots for the "IOError" class 
 */
#define ES_IOError__origin                                             9
#define ES_IOError_IOError                                             9
#define ES_IOError_NUM_CLASS_PROP                                      10

/**
 * Instance slots for "IOError" type 
 */
#define ES_IOError_NUM_INSTANCE_PROP                                   0

/**
 * 
 *    Local slots for methods in type IOError 
 */
#define ES_IOError_IOError_message                                     0


/**
 *   Class property slots for the "InternalError" class 
 */
#define ES_InternalError__origin                                       9
#define ES_InternalError_InternalError                                 9
#define ES_InternalError_NUM_CLASS_PROP                                10

/**
 * Instance slots for "InternalError" type 
 */
#define ES_InternalError_NUM_INSTANCE_PROP                             0

/**
 * 
 *    Local slots for methods in type InternalError 
 */
#define ES_InternalError_InternalError_message                         0


/**
 *   Class property slots for the "MemoryError" class 
 */
#define ES_MemoryError__origin                                         9
#define ES_MemoryError_MemoryError                                     9
#define ES_MemoryError_NUM_CLASS_PROP                                  10

/**
 * Instance slots for "MemoryError" type 
 */
#define ES_MemoryError_NUM_INSTANCE_PROP                               0

/**
 * 
 *    Local slots for methods in type MemoryError 
 */
#define ES_MemoryError_MemoryError_message                             0


/**
 *   Class property slots for the "OutOfBoundsError" class 
 */
#define ES_OutOfBoundsError__origin                                    9
#define ES_OutOfBoundsError_OutOfBoundsError                           9
#define ES_OutOfBoundsError_NUM_CLASS_PROP                             10

/**
 * Instance slots for "OutOfBoundsError" type 
 */
#define ES_OutOfBoundsError_NUM_INSTANCE_PROP                          0

/**
 * 
 *    Local slots for methods in type OutOfBoundsError 
 */
#define ES_OutOfBoundsError_OutOfBoundsError_message                   0


/**
 *   Class property slots for the "ReferenceError" class 
 */
#define ES_ReferenceError__origin                                      9
#define ES_ReferenceError_ReferenceError                               9
#define ES_ReferenceError_NUM_CLASS_PROP                               10

/**
 * Instance slots for "ReferenceError" type 
 */
#define ES_ReferenceError_NUM_INSTANCE_PROP                            0

/**
 * 
 *    Local slots for methods in type ReferenceError 
 */
#define ES_ReferenceError_ReferenceError_message                       0


/**
 *   Class property slots for the "ResourceError" class 
 */
#define ES_ResourceError__origin                                       9
#define ES_ResourceError_ResourceError                                 9
#define ES_ResourceError_NUM_CLASS_PROP                                10

/**
 * Instance slots for "ResourceError" type 
 */
#define ES_ResourceError_NUM_INSTANCE_PROP                             0

/**
 * 
 *    Local slots for methods in type ResourceError 
 */
#define ES_ResourceError_ResourceError_message                         0


/**
 *   Class property slots for the "StateError" class 
 */
#define ES_StateError__origin                                          9
#define ES_StateError_StateError                                       9
#define ES_StateError_NUM_CLASS_PROP                                   10

/**
 * Instance slots for "StateError" type 
 */
#define ES_StateError_NUM_INSTANCE_PROP                                0

/**
 * 
 *    Local slots for methods in type StateError 
 */
#define ES_StateError_StateError_message                               0


/**
 *   Class property slots for the "SyntaxError" class 
 */
#define ES_SyntaxError__origin                                         9
#define ES_SyntaxError_SyntaxError                                     9
#define ES_SyntaxError_NUM_CLASS_PROP                                  10

/**
 * Instance slots for "SyntaxError" type 
 */
#define ES_SyntaxError_NUM_INSTANCE_PROP                               0

/**
 * 
 *    Local slots for methods in type SyntaxError 
 */
#define ES_SyntaxError_SyntaxError_message                             0


/**
 *   Class property slots for the "TypeError" class 
 */
#define ES_TypeError__origin                                           9
#define ES_TypeError_TypeError                                         9
#define ES_TypeError_NUM_CLASS_PROP                                    10

/**
 * Instance slots for "TypeError" type 
 */
#define ES_TypeError_NUM_INSTANCE_PROP                                 0

/**
 * 
 *    Local slots for methods in type TypeError 
 */
#define ES_TypeError_TypeError_message                                 0


/**
 *   Class property slots for the "URIError" class 
 */
#define ES_URIError__origin                                            9
#define ES_URIError_URIError                                           9
#define ES_URIError_NUM_CLASS_PROP                                     10

/**
 * Instance slots for "URIError" type 
 */
#define ES_URIError_NUM_INSTANCE_PROP                                  0

/**
 * 
 *    Local slots for methods in type URIError 
 */
#define ES_URIError_URIError_message                                   0


/**
 *   Class property slots for the "Iterable" class 
 */
#define ES_Iterable__origin                                            0
#define ES_Iterable_get                                                0
#define ES_Iterable_getValues                                          1
#define ES_Iterable_NUM_CLASS_PROP                                     2

/**
 * Instance slots for "Iterable" type 
 */
#define ES_Iterable_NUM_INSTANCE_PROP                                  0


/**
 *   Class property slots for the "Iterator" class 
 */
#define ES_Iterator__origin                                            6
#define ES_Iterator_next                                               6
#define ES_Iterator_NUM_CLASS_PROP                                     7

/**
 * Instance slots for "Iterator" type 
 */
#define ES_Iterator_NUM_INSTANCE_PROP                                  0


/**
 *   Class property slots for the "JSON" class 
 */
#define ES_JSON__origin                                                6
#define ES_JSON_parse                                                  6
#define ES_JSON_stringify                                              7
#define ES_JSON_NUM_CLASS_PROP                                         8

/**
 * Instance slots for "JSON" type 
 */
#define ES_JSON_NUM_INSTANCE_PROP                                      0

/**
 * 
 *    Local slots for methods in type JSON 
 */
#define ES_JSON_parse_data                                             0
#define ES_JSON_parse_filter                                           1
#define ES_JSON_stringify_obj                                          0
#define ES_JSON_stringify_replacer                                     1
#define ES_JSON_stringify_indent                                       2


/**
 *   Class property slots for the "Math" class 
 */
#define ES_Math__origin                                                6
#define ES_Math__initializer__Math_initializer                         6
#define ES_Math_E                                                      7
#define ES_Math_LN2                                                    8
#define ES_Math_LN10                                                   9
#define ES_Math_LOG2E                                                  10
#define ES_Math_LOG10E                                                 11
#define ES_Math_PI                                                     12
#define ES_Math_SQRT1_2                                                13
#define ES_Math_SQRT2                                                  14
#define ES_Math_abs                                                    15
#define ES_Math_acos                                                   16
#define ES_Math_asin                                                   17
#define ES_Math_atan                                                   18
#define ES_Math_atan2                                                  19
#define ES_Math_ceil                                                   20
#define ES_Math_cos                                                    21
#define ES_Math_exp                                                    22
#define ES_Math_floor                                                  23
#define ES_Math_log10                                                  24
#define ES_Math_log                                                    25
#define ES_Math_max                                                    26
#define ES_Math_min                                                    27
#define ES_Math_pow                                                    28
#define ES_Math_random                                                 29
#define ES_Math_round                                                  30
#define ES_Math_sin                                                    31
#define ES_Math_sqrt                                                   32
#define ES_Math_tan                                                    33
#define ES_Math_NUM_CLASS_PROP                                         34

/**
 * Instance slots for "Math" type 
 */
#define ES_Math_NUM_INSTANCE_PROP                                      0

/**
 * 
 *    Local slots for methods in type Math 
 */
#define ES_Math_abs_value                                              0
#define ES_Math_acos_angle                                             0
#define ES_Math_asin_oper                                              0
#define ES_Math_atan_oper                                              0
#define ES_Math_atan2_y                                                0
#define ES_Math_atan2_x                                                1
#define ES_Math_ceil_oper                                              0
#define ES_Math_cos_angle                                              0
#define ES_Math_exp_power                                              0
#define ES_Math_floor_oper                                             0
#define ES_Math_log10_oper                                             0
#define ES_Math_log_oper                                               0
#define ES_Math_max_x                                                  0
#define ES_Math_max_y                                                  1
#define ES_Math_min_x                                                  0
#define ES_Math_min_y                                                  1
#define ES_Math_pow_num                                                0
#define ES_Math_pow_pow                                                1
#define ES_Math_round_num                                              0
#define ES_Math_sin_angle                                              0
#define ES_Math_sqrt_oper                                              0
#define ES_Math_tan_angle                                              0


/**
 *   Class property slots for the "Namespace" class 
 */
#define ES_Namespace__origin                                           6
#define ES_Namespace_NUM_CLASS_PROP                                    6

/**
 * Instance slots for "Namespace" type 
 */
#define ES_Namespace_NUM_INSTANCE_PROP                                 0


/**
 *   Class property slots for the "Reflect" class 
 */
#define ES_Reflect__origin                                             6
#define ES_Reflect_Reflect                                             6
#define ES_Reflect_name                                                7
#define ES_Reflect_type                                                8
#define ES_Reflect_typeName                                            9
#define ES_Reflect_NUM_CLASS_PROP                                      10

/**
 * Instance slots for "Reflect" type 
 */
#define ES_Reflect_obj                                                 0
#define ES_Reflect_NUM_INSTANCE_PROP                                   1

/**
 * 
 *    Local slots for methods in type Reflect 
 */
#define ES_Reflect_Reflect_obj                                         0


/**
 *   Class property slots for the "RegExp" class 
 */
#define ES_RegExp__origin                                              6
#define ES_RegExp_RegExp                                               6
#define ES_RegExp_lastIndex                                            7
#define ES_RegExp_set_lastIndex                                        8
#define ES_RegExp_exec                                                 9
#define ES_RegExp_global                                               10
#define ES_RegExp_ignoreCase                                           11
#define ES_RegExp_multiline                                            12
#define ES_RegExp_source                                               13
#define ES_RegExp_matched                                              14
#define ES_RegExp_replace                                              15
#define ES_RegExp_split                                                16
#define ES_RegExp_start                                                17
#define ES_RegExp_sticky                                               18
#define ES_RegExp_test                                                 19
#define ES_RegExp_NUM_CLASS_PROP                                       20

/**
 * Instance slots for "RegExp" type 
 */
#define ES_RegExp_NUM_INSTANCE_PROP                                    0

/**
 * 
 *    Local slots for methods in type RegExp 
 */
#define ES_RegExp_RegExp_pattern                                       0
#define ES_RegExp_RegExp_flags                                         1
#define ES_RegExp_set_lastIndex_value                                  0
#define ES_RegExp_exec_str                                             0
#define ES_RegExp_exec_start                                           1
#define ES_RegExp_replace_str                                          0
#define ES_RegExp_replace_replacement                                  1
#define ES_RegExp_split_target                                         0
#define ES_RegExp_test_str                                             0


/**
 *   Class property slots for the "Stream" class 
 */
#define ES_Stream__origin                                              0
#define ES_Stream_close                                                0
#define ES_Stream_flush                                                1
#define ES_Stream_read                                                 2
#define ES_Stream_write                                                3
#define ES_Stream_NUM_CLASS_PROP                                       4

/**
 * Instance slots for "Stream" type 
 */
#define ES_Stream_NUM_INSTANCE_PROP                                    0

/**
 * 
 *    Local slots for methods in type Stream 
 */
#define ES_Stream_close_graceful                                       0
#define ES_Stream_flush_graceful                                       0
#define ES_Stream_read_buffer                                          0
#define ES_Stream_read_offset                                          1
#define ES_Stream_read_count                                           2
#define ES_Stream_write_data                                           0


/**
 *   Class property slots for the "Type" class 
 */
#define ES_Type__origin                                                6
#define ES_Type_NUM_CLASS_PROP                                         6

/**
 * Instance slots for "Type" type 
 */
#define ES_Type_NUM_INSTANCE_PROP                                      0


/**
 *   Class property slots for the "StopIteration" class 
 */
#define ES_StopIteration__origin                                       6
#define ES_StopIteration_NUM_CLASS_PROP                                6

/**
 * Instance slots for "StopIteration" type 
 */
#define ES_StopIteration_NUM_INSTANCE_PROP                             0


/**
 *   Class property slots for the "XML" class 
 */
#define ES_XML__origin                                                 6
#define ES_XML_XML                                                     6
#define ES_XML__initializer__XML_initializer                           7
#define ES_XML_load                                                    8
#define ES_XML_save                                                    9
#define ES_XML_attribute                                               10
#define ES_XML_attributes                                              11
#define ES_XML_elements                                                12
#define ES_XML_name                                                    13
#define ES_XML_parent                                                  14
#define ES_XML_NUM_CLASS_PROP                                          15

/**
 * Instance slots for "XML" type 
 */
#define ES_XML_NUM_INSTANCE_PROP                                       0

/**
 * 
 *    Local slots for methods in type XML 
 */
#define ES_XML_XML_value                                               0
#define ES_XML_load_filename                                           0
#define ES_XML_save_filename                                           0
#define ES_XML_attribute_name                                          0
#define ES_XML_elements_name                                           0


/**
 *   Class property slots for the "XMLList" class 
 */
#define ES_XMLList__origin                                             6
#define ES_XMLList_XMLList                                             6
#define ES_XMLList_attribute                                           7
#define ES_XMLList_attributes                                          8
#define ES_XMLList_elements                                            9
#define ES_XMLList_name                                                10
#define ES_XMLList_parent                                              11
#define ES_XMLList_NUM_CLASS_PROP                                      12

/**
 * Instance slots for "XMLList" type 
 */
#define ES_XMLList_NUM_INSTANCE_PROP                                   0

/**
 * 
 *    Local slots for methods in type XMLList 
 */
#define ES_XMLList_attribute_name                                      0
#define ES_XMLList_elements_name                                       0

#define _ES_CHECKSUM_ejs 485298

#endif
